import fs from 'fs'
import path from 'path'
import Head from 'next/head'
import matter from 'gray-matter'

export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join('posts'))

  const posts = files.map(filename => {
    const markdownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8')
    const { data: frontmatter } = matter(markdownWithMeta)

    const slug = filename.split('.')[0]
    return {
      frontmatter,
      slug,
      href: `/posts/${slug}`
    }
  })

  return {
    props: {
      posts
    }
  }
}

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Bruno Krebs' Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Bruno Krebs' Blog</h1>

      {posts.map((post, index) => (
        <div key={index}>
          <h3>{post.frontmatter.title} / {post.frontmatter.date}</h3>
          <a href={post.href}>Read</a>
        </div>
      ))}
    </>
  )
}